package me.jeongrae.springkit.kit.client.generation

import kotlin.io.path.writeText
import me.jeongrae.springkit.kit.core.generation.GenerationAction
import me.jeongrae.springkit.kit.core.project.ProjectRoot

internal const val FIXED_README_CONTENT = """# SpringKit Starter

Generated by SpringKit.
Domain: jeongrae.me
"""

class ReadmeGenerationAction : GenerationAction {
    override fun execute(projectRoot: ProjectRoot) {
        projectRoot.path.resolve("README.md").writeText(FIXED_README_CONTENT)
    }
}
