package me.jeongrae.springkit

import java.nio.file.Path
import kotlin.io.path.Path
import kotlin.io.path.writeText
import me.jeongrae.springkit.generation.GenerationAction
import me.jeongrae.springkit.generation.GenerationActionRunner
import me.jeongrae.springkit.project.defaultProjectDirectoryFactory

internal const val APPLICATION_NAME = "SpringKit"
internal const val FIXED_README_CONTENT = """# SpringKit Starter

Generated by SpringKit.
Domain: jeongrae.me
"""

private val generateReadme =
    GenerationAction { projectRoot ->
        projectRoot.resolve("README.md").writeText(FIXED_README_CONTENT)
    }

private val fixedProjectRunner = GenerationActionRunner(listOf(generateReadme))

fun generateFixedProject(outputPath: Path): Path {
    val projectRoot = defaultProjectDirectoryFactory.create(outputPath)
    fixedProjectRunner.run(projectRoot)
    return projectRoot
}

fun main(args: Array<String>) {
    require(args.size == 1) { "Usage: springkit <output-path>" }

    val projectRoot = generateFixedProject(Path(args.single()))
    println("$APPLICATION_NAME generated a project at $projectRoot")
}
