package me.jeongrae.springkit.kit.api

import java.nio.file.FileAlreadyExistsException
import java.nio.file.Path
import kotlin.io.path.createDirectory
import kotlin.io.path.isDirectory
import kotlin.io.path.readText
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue
import org.junit.jupiter.api.io.TempDir

class SpringKitTest {
    @Test
    fun `고정 시작 프로젝트 생성을 종합한다`(@TempDir temporaryDirectory: Path) {
        val outputPath = temporaryDirectory.resolve("starter")

        main(arrayOf(outputPath.toString()))

        assertTrue(outputPath.isDirectory())
        assertEquals(
            """# SpringKit Starter

Generated by SpringKit.
Domain: jeongrae.me
""",
            outputPath.resolve("README.md").readText(),
        )
    }

    @Test
    fun `기존 프로젝트 루트를 덮어쓰지 않는다`(@TempDir temporaryDirectory: Path) {
        val outputPath = temporaryDirectory.resolve("starter").createDirectory()

        assertFailsWith<FileAlreadyExistsException> {
            main(arrayOf(outputPath.toString()))
        }
    }

    @Test
    fun `출력 경로 하나를 요구한다`() {
        assertFailsWith<IllegalArgumentException> {
            main(emptyArray())
        }
        assertFailsWith<IllegalArgumentException> {
            main(arrayOf("first", "second"))
        }
    }
}
